version: "3.9"

services:
  poker-frontend:
    build: ./poker-frontend
    ports:
      - "80:80"
    depends_on:
      - poker-backend
    restart: unless-stopped

  poker-backend:
    build: ./poker-backend
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/poker
      - PORT=5000
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
