name: Trigger auto deployment for poker-backend

on:
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/poker-backend-AutoDeployTrigger-0f2a00e1-b365-4e2e-8ec6-c6e870c8e9f5.yml'

  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.POKERBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.POKERBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.POKERBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/poker-backend
          registryUrl: pokertracker.azurecr.io
          registryUsername: ${{ secrets.POKERBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.POKERBACKEND_REGISTRY_PASSWORD }}
          containerAppName: poker-backend
          resourceGroup: myResourceGroup
          imageToBuild: pokertracker.azurecr.io/poker-backend:${{ github.sha }}

      - name: Delete old images from ACR
        run: |
          OLD_TAGS=$(az acr repository show-tags \
            --name pokertracker \
            --repository poker-backend \
            --orderby time_desc \
            --output tsv | tail -n +4)

          for TAG in $OLD_TAGS; do
            echo "Deleting poker-backend:$TAG"
            az acr repository delete \
              --name pokertracker \
              --image poker-backend:$TAG \
              --yes
          done