name: Trigger auto deployment for poker-frontend

on:
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/poker-frontend-AutoDeployTrigger-b435e7cb-7bf0-4bb8-8d64-424ad63ed500.yml'

  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.POKERFRONTEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.POKERFRONTEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.POKERFRONTEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/poker-frontend
          dockerfilePath: Dockerfile
          registryUrl: pokertracker.azurecr.io
          registryUsername: ${{ secrets.POKERFRONTEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.POKERFRONTEND_REGISTRY_PASSWORD }}
          containerAppName: poker-frontend
          resourceGroup: myResourceGroup
          imageToBuild: pokertracker.azurecr.io/poker-frontend:${{ github.sha }}
          buildArguments: |
            VITE_API_URL=https://api.pokerflow.live
